import { IKaleidoLayout } from "../../sharedcode/layoutInterface";

export const DEFAULT_LAYOUT: IKaleidoLayout = {
  layouts: [
    {
      sourceLayoutName: "clock",
      width: 952,
      height: 532,
      borderColor: "#111111",
      borderWidth: "2px",
      tallyColors: ["red", "green", "blue", "yellow"],
      elementLayouts: [
        {
          positionX: 10,
          positionY: 100,
          height: 110,
          width: 900,
          color: "#ffffff",
          fontSize: "105%",
          backgroundColor: "#000000aa",
        },
        {
          labelIndex: 0,
          positionX: 210,
          positionY: 490,
          height: 30,
          width: 200,
          color: "#ffffff",
          backgroundColor: "#000000aa",
          borderColor: "#ffffffff" // invisible because of full alpha
        },
        {
          labelIndex: 1,
          positionX: 490,
          positionY: 490,
          height: 30,
          width: 200,
          color: "#ffffff",
          backgroundColor: "#000000aa",
        },
        {
          labelIndex: 2,
          tallyIndex: 0,
          positionX: 180,
          positionY: 490,
          height: 30,
          width: 20,
          color: "#ff0000",
          backgroundColor: "transparent",
        },
        {
          labelIndex: 3,
          tallyIndex: 1,
          positionX: 700,
          positionY: 490,
          height: 30,
          width: 20,
          color: "#ff0000",
          backgroundColor: "transparent",
          borderOnlyTally: true,
        },
      ],
    },
    {
      sourceLayoutName: "largeQuarter",
      width: 952,
      height: 532,
      borderColor: "#111111",
      borderWidth: "2px",
      tallyColors: ["red", "green", "blue", "yellow"],
      elementLayouts: [
        {
          labelIndex: 0,
          height: 30,
          width: 200,
          positionX: 210,
          positionY: 490,
          color: "#ffffff",
          backgroundColor: "#000000aa",
        },
        {
          labelIndex: 1,
          height: 30,
          width: 200,
          positionX: 490,
          positionY: 490,
          color: "#ffffff",
          backgroundColor: "#000000aa",
        },
        {
          labelIndex: 2,
          tallyIndex: 0,
          height: 30,
          width: 20,
          positionX: 180,
          positionY: 490,
          color: "#ff0000",
          backgroundColor: "transparent",
        },
        {
          labelIndex: 3,
          tallyIndex: 1,
          height: 30,
          width: 20,
          positionX: 700,
          positionY: 490,
          color: "#ff0000",
          backgroundColor: "transparent",
        },
      ],
    },
    {
      sourceLayoutName: "small16th",
      width: 472,
      height: 264,
      borderColor: "#111111",
      borderWidth: "2px",
      tallyColors: ["red", "green", "blue", "yellow"],
      elementLayouts: [
        {
          labelIndex: 0,
          height: 30,
          width: 180,
          positionX: 40,
          positionY: 220,
          color: "#ffffff",
          backgroundColor: "#000000aa",
        },
        {
          labelIndex: 1,
          height: 30,
          width: 180,
          positionX: 240,
          positionY: 220,
          color: "#ffffff",
          backgroundColor: "#000000aa",
        },
        {
          labelIndex: 2,
          tallyIndex: 0,
          height: 30,
          width: 20,
          positionX: 10,
          positionY: 220,
          color: "#ff0000",
          backgroundColor: "transparent",
        },
        {
          labelIndex: 3,
          tallyIndex: 1,
          height: 30,
          width: 20,
          positionX: 430,
          positionY: 220,
          color: "#ff0000",
          backgroundColor: "transparent",
        },
      ],
    },
  ],
  sources: [
    {
      useSourceLayout: "clock",
      emberStateIndex: 0,
      positionX: 1,
      positionY: 2,
      sourceElements: [
        {
          clockTimeZone: "Europe/Copenhagen",
          clockFormat: "dk"
        }, {}, {}, {}, {},
      ]
    },
    {
      useSourceLayout: "largeQuarter",
      emberStateIndex: 1,
      positionX: 961,
      positionY: 2,
      sourceElements: [{}, {}, {}, {},],
    },
    {
      emberStateIndex: 2,
      positionX: 1,
      positionY: 542,
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],
    },
    {
      emberStateIndex: 3,
      positionX: 480,
      positionY: 542,
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],

    },
    {
      emberStateIndex: 4,
      positionX: 960,
      positionY: 542,
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],

    },
    {
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],
      emberStateIndex: 5,
      positionX: 1440,
      positionY: 542,
    },
    {
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],
      emberStateIndex: 6,
      positionX: 1,
      positionY: 811,
    },
    {
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],
      emberStateIndex: 7,
      positionX: 480,
      positionY: 811,
    },
    {
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],
      emberStateIndex: 8,
      positionX: 960,
      positionY: 811,
    },
    {
      useSourceLayout: "small16th",
      sourceElements: [{}, {}, {}, {},],
      emberStateIndex: 9,
      positionX: 1440,
      positionY: 811,
    },
  ],
};
