import { ISource } from "../../sharedcode/interfaces";

export const defaultLayout: ISource[] = [
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 200,
        positionX: 210,
        positionY: 490,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 200,
        positionX: 490,
        positionY: 490,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 180,
        positionY: 490,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 700,
        positionY: 490,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 0,
    positionX: 1,
    positionY: 2,
    width: 952,
    height: 532,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 200,
        positionX: 210,
        positionY: 490,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 200,
        positionX: 490,
        positionY: 490,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 180,
        positionY: 490,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 700,
        positionY: 490,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 1,
    positionX: 961,
    positionY: 2,
    width: 952,
    height: 532,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 2,
    positionX: 1,
    positionY: 542,
    width: 472,
    height: 264,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 3,
    positionX: 480,
    positionY: 542,
    width: 472,
    height: 264,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 4,
    positionX: 960,
    positionY: 542,
    width: 472,
    height: 264,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 5,
    positionX: 1440,
    positionY: 542,
    width: 472,
    height: 264,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 6,
    positionX: 1,
    positionY: 811,
    width: 472,
    height: 263,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 7,
    positionX: 480,
    positionY: 811,
    width: 472,
    height: 263,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 8,
    positionX: 960,
    positionY: 811,
    width: 472,
    height: 263,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
  {
    sourceElements: [
      {
        labelIndex: 0,
        height: 30,
        width: 180,
        positionX: 40,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 1,
        height: 30,
        width: 180,
        positionX: 240,
        positionY: 220,
        color: "#ffffff",
        backgroundColor: "#000000aa",
      },
      {
        labelIndex: 2,
        height: 30,
        width: 20,
        positionX: 10,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 0,
      },
      {
        labelIndex: 3,
        height: 30,
        width: 20,
        positionX: 430,
        positionY: 220,
        color: "#ff0000",
        backgroundColor: "transparent",
        tallyIndex: 1,
      },
    ],
    emberStateIndex: 9,
    positionX: 1440,
    positionY: 811,
    width: 472,
    height: 263,
    tallyColors: ["red", "green", "blue", "yellow"],
  },
];
